version: '3.9'

services:
  inminit-admin-panel-dev:
    container_name: inminit-admin-panel-latest
    image: inminit-admin-panel:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: ["nginx", "-g", "daemon off;"]
    